/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DateRange } from "./components/tw-daterange/types";
export { DateRange } from "./components/tw-daterange/types";
export namespace Components {
    interface TwDaterange {
        /**
          * Initial date range (start and end date object)
         */
        "initialRange"?: DateRange;
        /**
          * Whether the date range picker is open or not
         */
        "isOpen"?: boolean;
    }
}
export interface TwDaterangeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTwDaterangeElement;
}
declare global {
    interface HTMLTwDaterangeElement extends Components.TwDaterange, HTMLStencilElement {
    }
    var HTMLTwDaterangeElement: {
        prototype: HTMLTwDaterangeElement;
        new (): HTMLTwDaterangeElement;
    };
    interface HTMLElementTagNameMap {
        "tw-daterange": HTMLTwDaterangeElement;
    }
}
declare namespace LocalJSX {
    interface TwDaterange {
        /**
          * Initial date range (start and end date object)
         */
        "initialRange"?: DateRange;
        /**
          * Whether the date range picker is open or not
         */
        "isOpen"?: boolean;
        /**
          * Event emitted when the date range is updated
         */
        "onUpdate"?: (event: TwDaterangeCustomEvent<DateRange>) => void;
    }
    interface IntrinsicElements {
        "tw-daterange": TwDaterange;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tw-daterange": LocalJSX.TwDaterange & JSXBase.HTMLAttributes<HTMLTwDaterangeElement>;
        }
    }
}
